version: '3.8'
services:
  backend:
    image: backend:1.0.0
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/cloudservice
  
  database:
    image: postgres:16.2-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: khrapatiymv
      POSTGRES_PASSWORD: R0t4@dm1n
    volumes:
      - ./backend/infrastructure/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cloud.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
  frontend:
    image: frontend:1.0.0
    build: ./frontend
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules
      - ./frontend:/app

volumes:
  db-data:
  pgadmin-data: